stages:
  - build
  - deploy

variables:
  PROD_APP_DIR: /home/gitlab-runner/frontend/samatva-crm
  STAGE_APP_DIR: /home/gitlab-runner/frontend/samatva-crm-staging

# -----------------------
# BUILD (MAIN / PROD)
# -----------------------
build:prod:
  stage: build
  script:
    - cp $PROD_APP_DIR/.env .env
    - pnpm install --frozen-lockfile
    - pnpm run build
  artifacts:
    paths:
      - .next/
      - node_modules/
      - package.json
      - pnpm-lock.yaml
      - public/
    expire_in: 30 min
  only:
    - main
  tags:
    - prod-runner

# -----------------------
# BUILD (STAGING)
# -----------------------
build:staging:
  stage: build
  script:
    - cp $STAGE_APP_DIR/.env .env
    - pnpm install --frozen-lockfile
    - pnpm run build
  artifacts:
    paths:
      - .next/
      - node_modules/
      - package.json
      - pnpm-lock.yaml
      - public/
    expire_in: 30 min
  only:
    - staging
  tags:
    - stage-runner

# -----------------------
# DEPLOY PROD
# -----------------------
deploy:production:
  stage: deploy
  script:
    - mkdir -p $PROD_APP_DIR
    - cp -r .next node_modules package.json pnpm-lock.yaml public ecosystem.config.js .env $PROD_APP_DIR/
    - cd $PROD_APP_DIR
    - pm2 reload ecosystem.config.js --only samatva-crm || pm2 start ecosystem.config.js --only samatva-crm
    - pm2 save
  only:
    - main
  tags:
    - prod-runner
  needs:
    - build:prod

# -----------------------
# DEPLOY STAGING
# -----------------------
deploy:staging:
  stage: deploy
  script:
    - mkdir -p $STAGE_APP_DIR
    - cp -r .next node_modules package.json pnpm-lock.yaml public ecosystem.config.js .env $STAGE_APP_DIR/
    - cd $STAGE_APP_DIR
    - pm2 reload ecosystem.config.js --only samatva-crm-staging || pm2 start ecosystem.config.js --only samatva-crm-staging
    - pm2 save
  only:
    - staging
  tags:
    - stage-runner
  needs:
    - build:staging
