import type { TemplateData } from '../types/template.types';

export const mockTemplates: TemplateData[] = [
  {
    id: '1',
    name: 'ICICI Settlement Offer',
    description: 'Settlement offer email template for ICICI bank customers',
    channel: 'email',
    type: 'email',
    status: 'approved',
    bankTag: 'ICICI',
    content: {
      subject: 'Special Settlement Offer for Your Account',
      body: 'Dear {{customer_name}},\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n\nUt enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\n\nAmount: ₹{{outstanding_amount}}\nOffer: ₹{{settlement_amount}} ({{discount_percentage}}% discount)\nValid Until: {{expiry_date}}\n\nExcepteur sint occaecat cupidatat non proident:\n• Sunt in culpa qui officia deserunt mollit anim\n• Id est laborum sed ut perspiciatis unde omnis\n• Iste natus error sit voluptatem accusantium\n• Doloremque laudantium totam rem aperiam\n\nEaque ipsa quae ab illo inventore veritatis:\nPhone: 1800-XXX-XXXX\nEmail: settlements@example.com\n\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa.\n\nBest regards,\nICICI Settlement Team',
    },
    createdAt: '2024-01-15',
    modifiedBy: 'John Doe',
    tags: ['Bank-specific', 'Settlement'],
  },
  {
    id: '2',
    name: 'SMS Reminder',
    description: 'General SMS reminder template for all banks',
    channel: 'sms',
    type: 'sms',
    status: 'approved',
    bankTag: 'All Banks',
    content:
      'Hi {{customer_name}}, Your settlement offer expires today. Call us at 1800-XXX-XXXX to proceed.',
    createdAt: '2024-01-14',
    modifiedBy: 'Jane Smith',
    tags: ['General', 'Reminder'],
  },
  {
    id: '3',
    name: 'WhatsApp Follow-up',
    description: 'Follow-up WhatsApp message template for IndusInd bank',
    channel: 'whatsapp',
    type: 'whatsapp',
    status: 'pending',
    bankTag: 'IndusInd',
    content:
      "Hello {{customer_name}}! 👋 We noticed you haven't responded to our settlement offer. This is a limited-time opportunity...",
    createdAt: '2024-01-13',
    modifiedBy: 'Mike Johnson',
    tags: ['Follow-up'],
  },
  {
    id: '4',
    name: 'HDFC Payment Reminder',
    description: 'Payment reminder email template for HDFC bank customers',
    channel: 'email',
    type: 'email',
    status: 'approved',
    bankTag: 'HDFC',
    content: {
      subject: 'Payment Reminder - Action Required',
      body: 'Dear {{customer_name}}, This is a friendly reminder about your upcoming payment of ₹{{payment_amount}} due on {{due_date}}...',
    },
    createdAt: '2024-01-12',
    modifiedBy: 'Sarah Williams',
    tags: ['Reminder'],
  },
  {
    id: '5',
    name: 'Axis EMI Offer',
    description: 'EMI conversion offer SMS for Axis bank customers',
    channel: 'sms',
    type: 'sms',
    status: 'approved',
    bankTag: 'Axis',
    content:
      'Hi {{customer_name}}, Special EMI offer available! Convert ₹{{amount}} to easy installments. Call 1800-XXX-XXXX',
    createdAt: '2024-01-11',
    modifiedBy: 'David Brown',
    tags: ['Settlement'],
  },
  {
    id: '6',
    name: 'General Welcome Email',
    description: 'Welcome email template for new customers across all banks',
    channel: 'email',
    type: 'email',
    status: 'approved',
    bankTag: 'All Banks',
    content: {
      subject: 'Welcome to Our Settlement Program',
      body: 'Welcome {{customer_name}}! We are here to help you settle your outstanding dues with flexible payment options...',
    },
    createdAt: '2024-01-10',
    modifiedBy: 'Emily Davis',
    tags: ['General'],
  },
  {
    id: '7',
    name: 'WhatsApp Payment Confirmation',
    description: 'Payment confirmation WhatsApp message template',
    channel: 'whatsapp',
    type: 'whatsapp',
    status: 'approved',
    bankTag: 'All Banks',
    content:
      '✅ Payment Received! Thank you {{customer_name}} for your payment of ₹{{amount}}. Reference: {{ref_number}}',
    createdAt: '2024-01-09',
    modifiedBy: 'Robert Taylor',
    tags: ['General'],
  },
  {
    id: '8',
    name: 'ICICI Final Notice',
    description: 'Final notice email template for ICICI bank customers',
    channel: 'email',
    type: 'email',
    status: 'draft',
    bankTag: 'ICICI',
    content: {
      subject: 'URGENT: Final Notice - Immediate Action Required',
      body: 'URGENT: Dear {{customer_name}}, This is your final notice regarding the outstanding amount of ₹{{amount}}...',
    },
    createdAt: '2024-01-08',
    modifiedBy: 'Lisa Anderson',
    tags: ['Reminder'],
  },
  {
    id: '9',
    name: 'Settlement Success SMS',
    description: 'Settlement success confirmation SMS for all banks',
    channel: 'sms',
    type: 'sms',
    status: 'approved',
    bankTag: 'All Banks',
    content:
      'Congratulations {{customer_name}}! Your settlement has been processed successfully. Amount: ₹{{amount}}',
    createdAt: '2024-01-07',
    modifiedBy: 'Michael Clark',
    tags: ['General'],
  },
  {
    id: '10',
    name: 'IndusInd Follow-up Email',
    description: 'Follow-up email template for IndusInd bank customers',
    channel: 'email',
    type: 'email',
    status: 'pending',
    bankTag: 'IndusInd',
    content: {
      subject: 'Following Up on Your Settlement Proposal',
      body: 'Dear {{customer_name}}, We wanted to follow up on our recent settlement proposal. Our records show...',
    },
    createdAt: '2024-01-06',
    modifiedBy: 'Jennifer Martinez',
    tags: ['Follow-up'],
  },
  {
    id: '11',
    name: 'WhatsApp Offer Alert',
    description: 'Special offer WhatsApp alert for HDFC bank customers',
    channel: 'whatsapp',
    type: 'whatsapp',
    status: 'approved',
    bankTag: 'HDFC',
    content:
      '🎉 Special Offer for {{customer_name}}! Settle your HDFC dues with 40% discount. Valid till {{expiry_date}}',
    createdAt: '2024-01-05',
    modifiedBy: 'Christopher Lee',
    tags: ['Settlement'],
  },
  {
    id: '12',
    name: 'Axis Verification SMS',
    description: 'Mobile verification SMS for Axis bank customers',
    channel: 'sms',
    type: 'sms',
    status: 'approved',
    bankTag: 'Axis',
    content:
      'Dear {{customer_name}}, Please verify your mobile number by replying YES to this message.',
    createdAt: '2024-01-04',
    modifiedBy: 'Amanda White',
    tags: ['General'],
  },
];
