export interface FinancialInstitution {
  id: string;
  name: string;
  type: string;
  ifscCode: string;
  branch: string;
  contactPerson: string;
  email: string;
  phone: string;
  status: string;
  address?: string;
  city?: string;
  state?: string;
  pincode?: string;
  createdAt: string;
}

export const financialInstitutionsData: FinancialInstitution[] = [
  {
    id: '1',
    name: 'State Bank of India',
    type: 'Bank',
    ifscCode: 'SBIN0001234',
    branch: 'Connaught Place',
    contactPerson: 'Rajesh Kumar',
    email: 'rajesh.kumar@sbi.co.in',
    phone: '+91 9876543210',
    status: 'Active',
    address: 'Parliament Street',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110001',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'HDFC Bank',
    type: 'Bank',
    ifscCode: 'HDFC0000123',
    branch: 'Bandra West',
    contactPerson: 'Priya Sharma',
    email: 'priya.sharma@hdfcbank.com',
    phone: '+91 9876543211',
    status: 'Active',
    address: 'Linking Road',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400050',
    createdAt: '2024-01-20',
  },
  {
    id: '3',
    name: 'ICICI Bank',
    type: 'Bank',
    ifscCode: 'ICIC0001234',
    branch: 'MG Road',
    contactPerson: 'Amit Patel',
    email: 'amit.patel@icicibank.com',
    phone: '+91 9876543212',
    status: 'Active',
    address: 'MG Road',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560001',
    createdAt: '2024-02-01',
  },
  {
    id: '4',
    name: 'Axis Bank',
    type: 'Bank',
    ifscCode: 'UTIB0001234',
    branch: 'Park Street',
    contactPerson: 'Sneha Gupta',
    email: 'sneha.gupta@axisbank.com',
    phone: '+91 9876543213',
    status: 'Active',
    address: 'Park Street',
    city: 'Kolkata',
    state: 'West Bengal',
    pincode: '700016',
    createdAt: '2024-02-10',
  },
  {
    id: '5',
    name: 'Punjab National Bank',
    type: 'Bank',
    ifscCode: 'PUNB0123400',
    branch: 'Civil Lines',
    contactPerson: 'Vikram Singh',
    email: 'vikram.singh@pnb.co.in',
    phone: '+91 9876543214',
    status: 'Active',
    address: 'Mall Road',
    city: 'Ludhiana',
    state: 'Punjab',
    pincode: '141001',
    createdAt: '2024-02-15',
  },
  {
    id: '6',
    name: 'Bank of Baroda',
    type: 'Bank',
    ifscCode: 'BARB0VAJIRA',
    branch: 'Vadodara Main',
    contactPerson: 'Anjali Mehta',
    email: 'anjali.mehta@bankofbaroda.com',
    phone: '+91 9876543215',
    status: 'Active',
    address: 'RC Dutt Road',
    city: 'Vadodara',
    state: 'Gujarat',
    pincode: '390005',
    createdAt: '2024-03-01',
  },
  {
    id: '7',
    name: 'Kotak Mahindra Bank',
    type: 'Bank',
    ifscCode: 'KKBK0001234',
    branch: 'Nariman Point',
    contactPerson: 'Rahul Kapoor',
    email: 'rahul.kapoor@kotak.com',
    phone: '+91 9876543216',
    status: 'Active',
    address: 'Nariman Point',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400021',
    createdAt: '2024-03-10',
  },
  {
    id: '8',
    name: 'IndusInd Bank',
    type: 'Bank',
    ifscCode: 'INDB0001234',
    branch: 'Whitefield',
    contactPerson: 'Kavita Reddy',
    email: 'kavita.reddy@indusind.com',
    phone: '+91 9876543217',
    status: 'Active',
    address: 'ITPL Main Road',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560066',
    createdAt: '2024-03-15',
  },
  {
    id: '9',
    name: 'Yes Bank',
    type: 'Bank',
    ifscCode: 'YESB0001234',
    branch: 'Powai',
    contactPerson: 'Suresh Nair',
    email: 'suresh.nair@yesbank.in',
    phone: '+91 9876543218',
    status: 'Inactive',
    address: 'Hiranandani Gardens',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400076',
    createdAt: '2024-04-01',
  },
  {
    id: '10',
    name: 'Federal Bank',
    type: 'Bank',
    ifscCode: 'FDRL0001234',
    branch: 'Kochi Main',
    contactPerson: 'Maya Thomas',
    email: 'maya.thomas@federalbank.co.in',
    phone: '+91 9876543219',
    status: 'Active',
    address: 'MG Road',
    city: 'Kochi',
    state: 'Kerala',
    pincode: '682016',
    createdAt: '2024-04-10',
  },
  {
    id: '11',
    name: 'IDBI Bank',
    type: 'Bank',
    ifscCode: 'IBKL0001234',
    branch: 'Nehru Place',
    contactPerson: 'Deepak Verma',
    email: 'deepak.verma@idbibank.co.in',
    phone: '+91 9876543220',
    status: 'Active',
    address: 'Nehru Place',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110019',
    createdAt: '2024-04-20',
  },
  {
    id: '12',
    name: 'Canara Bank',
    type: 'Bank',
    ifscCode: 'CNRB0001234',
    branch: 'Jayanagar',
    contactPerson: 'Lakshmi Iyer',
    email: 'lakshmi.iyer@canarabank.com',
    phone: '+91 9876543221',
    status: 'Inactive',
    address: '4th Block',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560011',
    createdAt: '2024-05-01',
  },
];
