export interface Nbfc {
  id: string;
  name: string;
  category: string;
  registrationNumber: string;
  headquarter: string;
  contactPerson: string;
  email: string;
  phone: string;
  status: string;
  address?: string;
  city?: string;
  state?: string;
  pincode?: string;
  website?: string;
  establishedYear?: number;
  createdAt: string;
}

export const nbfcData: Nbfc[] = [
  {
    id: '1',
    name: 'Bajaj Finance Limited',
    category: 'Loan Company',
    registrationNumber: 'N-13.00443',
    headquarter: 'Pune',
    contactPerson: 'Rajeev Jain',
    email: 'rajeev.jain@bajajfinserv.in',
    phone: '+91 9876543301',
    status: 'Active',
    address: 'Bajaj Finserv Corporate Office',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411045',
    website: 'www.bajajfinserv.in',
    establishedYear: 2007,
    createdAt: '2024-01-10',
  },
  {
    id: '2',
    name: 'Mahindra & Mahindra Financial Services',
    category: 'Asset Finance',
    registrationNumber: 'N-13.00281',
    headquarter: 'Mumbai',
    contactPerson: 'Ramesh Iyer',
    email: 'ramesh.iyer@mahindra.com',
    phone: '+91 9876543302',
    status: 'Active',
    address: 'Gateway Building',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400001',
    website: 'www.mahindrafinance.com',
    establishedYear: 1991,
    createdAt: '2024-01-15',
  },
  {
    id: '3',
    name: 'Shriram Transport Finance Company',
    category: 'Asset Finance',
    registrationNumber: 'N-13.00210',
    headquarter: 'Chennai',
    contactPerson: 'Umesh Revankar',
    email: 'umesh.revankar@shriramtransport.com',
    phone: '+91 9876543303',
    status: 'Active',
    address: 'Wockhardt Towers',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600006',
    website: 'www.stfc.in',
    establishedYear: 1979,
    createdAt: '2024-01-20',
  },
  {
    id: '4',
    name: 'Muthoot Finance Ltd',
    category: 'Loan Company',
    registrationNumber: 'N-13.00609',
    headquarter: 'Kochi',
    contactPerson: 'George Alexander Muthoot',
    email: 'george@muthootfinance.com',
    phone: '+91 9876543304',
    status: 'Active',
    address: 'Muthoot Chambers',
    city: 'Kochi',
    state: 'Kerala',
    pincode: '682011',
    website: 'www.muthootfinance.com',
    establishedYear: 1939,
    createdAt: '2024-02-01',
  },
  {
    id: '5',
    name: 'HDFC Credila Financial Services',
    category: 'Loan Company',
    registrationNumber: 'N-14.01958',
    headquarter: 'Mumbai',
    contactPerson: 'Ajay Bohora',
    email: 'ajay.bohora@credila.com',
    phone: '+91 9876543305',
    status: 'Active',
    address: 'One World Center',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400013',
    website: 'www.credila.com',
    establishedYear: 2006,
    createdAt: '2024-02-10',
  },
  {
    id: '6',
    name: 'L&T Finance Holdings',
    category: 'Infrastructure Finance',
    registrationNumber: 'N-13.01429',
    headquarter: 'Mumbai',
    contactPerson: 'Dinanath Dubhashi',
    email: 'dinanath.dubhashi@ltfs.com',
    phone: '+91 9876543306',
    status: 'Active',
    address: 'Brindavan',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400051',
    website: 'www.ltfs.com',
    establishedYear: 2008,
    createdAt: '2024-02-15',
  },
  {
    id: '7',
    name: 'Tata Capital Financial Services',
    category: 'Loan Company',
    registrationNumber: 'N-14.01687',
    headquarter: 'Mumbai',
    contactPerson: 'Rajiv Sabharwal',
    email: 'rajiv.sabharwal@tatacapital.com',
    phone: '+91 9876543307',
    status: 'Active',
    address: 'Shree Shakambhari Corporate Park',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400059',
    website: 'www.tatacapital.com',
    establishedYear: 2007,
    createdAt: '2024-03-01',
  },
  {
    id: '8',
    name: 'Aditya Birla Finance Limited',
    category: 'Loan Company',
    registrationNumber: 'N-14.02307',
    headquarter: 'Mumbai',
    contactPerson: 'Ajay Srinivasan',
    email: 'ajay.srinivasan@adityabirlacapital.com',
    phone: '+91 9876543308',
    status: 'Inactive',
    address: 'Indian Rayon Compound',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400030',
    website: 'www.adityabirlacapital.com',
    establishedYear: 2007,
    createdAt: '2024-03-10',
  },
];
